const test=require('node:test'),assert=require('node:assert/strict');
const {createFrontendBridge}=require('../src/frontendBridge.cjs');
async function fixture(t,upstream){const calls=[];const server=createFrontendBridge({bearerToken:'test-only-token',fetch:async(url,options)=>{calls.push({url,options});if(upstream)return upstream();return {status:200,json:async()=>({status:'PROCESSING'})};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));return {calls,request:(route,options={})=>fetch(`http://127.0.0.1:${server.address().port}/api${route}`,options)};}
test('local bridge forwards execution idempotency but never exposes bearer',async t=>{const f=await fixture(t);const r=await f.request('/batches/b/execute',{method:'POST',headers:{Origin:'http://127.0.0.1:5173','Content-Type':'application/json','Idempotency-Key':'stable-key'},body:'{}'});assert.equal(r.status,200);assert.equal(f.calls[0].options.headers['Idempotency-Key'],'stable-key');assert.equal(f.calls[0].options.headers.Authorization,'Bearer test-only-token');assert.ok(!(await r.text()).includes('test-only-token'));});
test('mutations without same-origin header are rejected before upstream',async t=>{const f=await fixture(t);assert.equal((await f.request('/batches',{method:'POST',body:'{}'})).status,403);assert.equal(f.calls.length,0);});
test('cross-origin request cannot invoke local engine',async t=>{const f=await fixture(t);assert.equal((await f.request('/quote',{method:'POST',headers:{Origin:'https://attacker.example'},body:'{}'})).status,403);assert.equal(f.calls.length,0);});
test('bridge excludes unapproved routes and query token',async t=>{const f=await fixture(t);assert.equal((await f.request('/batches/b/refund',{method:'POST',headers:{Origin:'http://127.0.0.1:5173'},body:'{}'})).status,404);assert.equal((await f.request('/batches/b?token=secret')).status,404);assert.equal(f.calls.length,0);});
test('bridge allows the read-only batch progress projection',async t=>{const f=await fixture(t);const r=await f.request('/batches/b/progress');assert.equal(r.status,200);assert.equal(f.calls[0].url,'http://127.0.0.1:3000/batches/b/progress');});
test('bridge forwards funded-batch resume and excludes test-only direct execution',async t=>{const f=await fixture(t);const r=await f.request('/batches/b/resume',{method:'POST',headers:{Origin:'http://127.0.0.1:5173','Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200);assert.equal(f.calls[0].url,'http://127.0.0.1:3000/batches/b/resume');assert.equal(f.calls[0].options.headers.Authorization,'Bearer test-only-token');assert.equal((await f.request('/batches/b/execute-direct',{method:'POST',headers:{Origin:'http://127.0.0.1:5173'},body:'{}'})).status,404);assert.equal(f.calls.length,1);});
test('submission timeout never claims nothing was sent',async t=>{const f=await fixture(t,()=>{throw Error('timeout');});const r=await f.request('/batches/b/execute',{method:'POST',headers:{Origin:'http://127.0.0.1:5173'},body:'{}'});assert.equal(r.status,502);assert.match((await r.json()).error,/may have reached/);});
